// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpJbL-v5bvJDSAfhDSqhvNw--ScMZujvs',
    appId: '1:835629827698:web:306647a1e1df9782e024eb',
    messagingSenderId: '835629827698',
    projectId: 'persistencia-ec152',
    authDomain: 'persistencia-ec152.firebaseapp.com',
    storageBucket: 'persistencia-ec152.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnZwNyWBvSZNzIXly_TtYO14xDXmok3G0',
    appId: '1:835629827698:android:edcc3a1fd580aca3e024eb',
    messagingSenderId: '835629827698',
    projectId: 'persistencia-ec152',
    storageBucket: 'persistencia-ec152.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBn5XvIjZ6HTWJ49rj68lGcnGT1l67BR0',
    appId: '1:835629827698:ios:2984e276c24c4e89e024eb',
    messagingSenderId: '835629827698',
    projectId: 'persistencia-ec152',
    storageBucket: 'persistencia-ec152.appspot.com',
    iosBundleId: 'com.example.agendarConsultas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBn5XvIjZ6HTWJ49rj68lGcnGT1l67BR0',
    appId: '1:835629827698:ios:2984e276c24c4e89e024eb',
    messagingSenderId: '835629827698',
    projectId: 'persistencia-ec152',
    storageBucket: 'persistencia-ec152.appspot.com',
    iosBundleId: 'com.example.agendarConsultas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtk6crGB0eYaH4dPcCUvXDERHgD3qUMDw',
    appId: '1:835629827698:web:22bd9b413294bbafe024eb',
    messagingSenderId: '835629827698',
    projectId: 'persistencia-ec152',
    authDomain: 'persistencia-ec152.firebaseapp.com',
    storageBucket: 'persistencia-ec152.appspot.com',
  );

}